server:
  port: 7777


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProducerKafka
    username: root
    password: Pavilion@12




  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true




